//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVinilos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int idCancion { get; set; }
        public Nullable<int> idDisco { get; set; }
        public string nombre { get; set; }
        public string enlace { get; set; }
        public Nullable<int> cara { get; set; }
    
        public virtual Disco Disco { get; set; }
    }
}
