//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVinilos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duda
    {
        public int idDuda { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idAdmin { get; set; }
        public string titutlo { get; set; }
        public string contenido { get; set; }
        public string respuesta { get; set; }
        public System.DateTime publicacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
