//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVinilos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementoPedido
    {
        public int idElemento { get; set; }
        public Nullable<int> idDisco { get; set; }
        public double precio { get; set; }
        public int cantidad { get; set; }
        public int idPedido { get; set; }
    
        public virtual Disco Disco { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
