//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVinilos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenArtista
    {
        public int idImagen { get; set; }
        public int idArtista { get; set; }
        public string enlace { get; set; }
    
        public virtual Artista Artista { get; set; }
    }
}
