//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVinilos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tienda
    {
        public int idTienda { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public string calle { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
        public System.TimeSpan apertura { get; set; }
        public System.TimeSpan cierre { get; set; }
    }
}
